### ISSUE TITLE
Minimal implementation example / pseudo-code

### ISSUE THREAD

**Issue by JCBrouwer** [bair-climate-initiative/xT#6]
Hi there, thanks for the interesting paper and for open sourcing the code!

I've been digging into the repo and am having a hard time understanding which parts specifically comprise the main contribution.

Based on the diagram from the README, I think that [this function of the trainer](https://github.com/bair-climate-initiative/xT/blob/main/xt/trainer.py#L212) is implementing nested tokenization / patchification. However, I can't find anywhere that this function is actually called!

It seems that the hierarchical region encoder / context-aware encoding is happening in [this part of the `EncoderDecoder` class](https://github.com/bair-climate-initiative/xT/blob/main/xt/models/decoders/decoder.py#L293). However, it's not clear what the encoder and decoder represent here as the `ContextEncoderConfig` defines the decoder.

The `ClsEvaluator`  seems to have [a function](https://github.com/bair-climate-initiative/xT/blob/main/xt/evaluator.py#L99) which implements the inference context encoding end-to-end, yet this also seems to never actually be called...

I wonder if you could provide some high-level pseudo-code of the entire process (compared to regular non-xT training), and some pointers to the specific parts of the repository which implement each subroutine. I think this would really help clarify the method and make it easier for others to use it as well.

**Comment by RitwikGupta** [comment]
Hey @JCBrouwer!

Thanks for your interest in xT. We hope that you have been finding it to be useful.

In our paper, we experiment with classification (iNaturalist), segmentation (xView3), and detection (COCO) datasets. We implement nested tokenization and structure the encoder/decoder slightly differently between the setups to gain training speed efficiencies.

We implement the `EncoderDecoder` class in which we combine the region encoder, context encoder, and task decoder. For classification, we fuse the context encoder and task-specific decoder (a cls head in this case) in `decoder.py`. We do this primarily for efficiency purposes. In particular, there are two equivalent implementations:

Consider an image with 4 regions
```
|1 |2 |
-------
|3| 4|
```

The current implementation takes in the whole image, splits it into four regions (each fed through the region encoder), and passes it to context encoder while keeping everything in memory.  The pseudo code will look like

```python
input: x: 1 x 3 x 2H x 2W
# ---------------------------------Encoder-----------------------------------
region1, region2, region3, region4 = split(x.cuda()) # each region is 1 x 3 x H x W, all in GPU
feature1, feature2, feature3, feature4  = region_encoder([region1,region2,region3,,region4 ])
# ---------------------------------Context Encoder (XL) -----------------------------------
out1, mem = context_encoder([feature1, feature2],context=None) # in each output, stopGrad is applied to mem
out1 = task_head(out1)
out2, mem = context_encoder([feature2, feature3],context= mem)
out2 = task_head(out2)
out3, mem = context_encoder([feature3, feature4],context= mem)
out3 = task_head(out3)
---------------------------------loss -------------------------------------------
 loss = task_loss([out1, out2, out3], [target1, target2, target3])
```

The second implementation that we use for xView and COCO is
```python
input: x: 1 x 3 x 2H x 2W
# ---------------------------------Trainer Preprocessing-----------------------------------
region1,region2,region3,,region4 = split(x) # each region is 1 x 3 x H x W, all in CPU
# -------------------------------- Pass 1 ------------------------------------------------
feature1, feature2 = region_encoder([region1.cuda(), region2.cuda()])
out1, mem = context_encoder([feature1, feature2], context=None)
out1 = task_head(out1)
loss = task_loss(out1, target1)
# -------------------------------- Pass 2 ------------------------------------------------
feature2, feature3 = region_encoder([region2.cuda(), region3.cuda()])
out2, mem = context_encoder([feature2, feature3], context= mem)
out2 = task_head(out2)
loss2 = task_loss(out2, target1)
# -------------------------------- Pass 3 ------------------------------------------------
feature3, feature4 = region_encoder([region3.cuda(), region4.cuda()])
out3, mem = context_encoder([feature3, feature4], context= mem)
out3 = task_head(out3)
loss3 = task_loss(out3, target1)
```

This helps save CPU memory in the case of extremely large images like in xView3. Since iNaturalist images fit entirely in memory, we do not want to re-encode regions if they fit in memory.

In effect, we had three codebases for the same framework. We need to refactor the xT codebase so that one interface can be used for any input dataset. The unused code you link to are from our xView3 implementation that we accidentally did not remove before release.

We will be releasing a significant refactor to the xT code in a bit along with the xView3 and COCO experiments (amongst others that we've been running in the meantime).

Hope this helps!

**Comment by JCBrouwer** [comment]
Thanks for the thorough explanation! Looking forward to the refactored release :)
